version: '3.1'
services:
  client:
    build: ./client
    ports:
      - "3333:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:7000/api
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build: ./server
    ports:
      - '7000:7000'
    depends_on:
      - db
    links:
      - db
  db:
    build: ./db
    image: mongo:latest
    env_file: .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - '$HOME/dockerdbcontainer:/data/db'
volumes:
  protrackerDB:







